import { FileText, AlertTriangle, Shield, Code, Ban, Gavel } from "lucide-react"

export default function TermsOfService() {
  return (
    <div className="space-y-12">
      {/* Header */}
      <div className="flex flex-col items-center">
        <h1 className="text-4xl md:text-5xl font-bold text-center text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted text-center">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      {/* Introduction */}
      <div className="glass-panel">
        <p className="text-lg leading-relaxed text-muted mb-4">
          These Terms of Service ("Terms") govern your access to and use of Per4ex.org ("we," "our," or "us"). By accessing or using our website and services, you agree to be bound by these Terms.
        </p>
        <p className="text-muted">
          If you do not agree to these Terms, please do not use our services.
        </p>
      </div>

      {/* Acceptance of Terms */}
      <div className="glass-panel border-l-4 border-l-accent">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <FileText className="w-6 h-6 text-accent" />
          Acceptance of Terms
        </h2>
        <div className="space-y-3 text-muted">
          <p>
            By accessing or using Per4ex.org, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. These Terms constitute a legally binding agreement between you and Per4ex.org.
          </p>
          <p>
            We reserve the right to modify these Terms at any time. Your continued use of our services after any such changes constitutes your acceptance of the new Terms.
          </p>
        </div>
      </div>

      {/* Use of Services */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <Code className="w-6 h-6 text-accent" />
          Use of Services
        </h2>
        <div className="space-y-4 text-muted">
          <div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Permitted Use</h3>
            <p>You may use our website and services for lawful purposes only. You agree to:</p>
            <ul className="space-y-2 list-disc pl-6 mt-2">
              <li>Use the services in accordance with all applicable laws and regulations</li>
              <li>Respect intellectual property rights</li>
              <li>Provide accurate information when interacting with our services</li>
              <li>Maintain the security of your account credentials (if applicable)</li>
            </ul>
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Prohibited Activities</h3>
            <p>You agree not to:</p>
            <ul className="space-y-2 list-disc pl-6 mt-2">
              <li>Use the services for any illegal or unauthorized purpose</li>
              <li>Attempt to gain unauthorized access to our systems or networks</li>
              <li>Interfere with or disrupt the services or servers</li>
              <li>Transmit any viruses, malware, or harmful code</li>
              <li>Use automated systems (bots, scrapers) to access the services without permission</li>
              <li>Reverse engineer, decompile, or disassemble any part of our services</li>
              <li>Use the services to harass, abuse, or harm others</li>
              <li>Impersonate any person or entity or misrepresent your affiliation</li>
            </ul>
          </div>
        </div>
      </div>

      {/* AI Services */}
      <div className="glass-panel border-l-4 border-l-accent">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <Shield className="w-6 h-6 text-accent" />
          AI Services (Catalyst)
        </h2>
        <div className="space-y-4 text-muted">
          <p>
            Our Catalyst AI services, including chat and voice features, are provided "as is" for informational and demonstration purposes.
          </p>
          <div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Service Limitations</h3>
            <ul className="space-y-2 list-disc pl-6">
              <li>AI responses are generated by third-party AI models and may contain inaccuracies</li>
              <li>We do not guarantee the accuracy, completeness, or reliability of AI-generated content</li>
              <li>AI services may be unavailable due to maintenance, updates, or technical issues</li>
              <li>Voice features require browser permissions and may not work on all devices</li>
            </ul>
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground mb-2">User Responsibilities</h3>
            <ul className="space-y-2 list-disc pl-6">
              <li>Do not rely solely on AI-generated content for critical decisions</li>
              <li>Verify important information from authoritative sources</li>
              <li>Do not use AI services to generate harmful, illegal, or unethical content</li>
              <li>Respect rate limits and usage restrictions</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Intellectual Property */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4">Intellectual Property</h2>
        <div className="space-y-3 text-muted">
          <p>
            All content on Per4ex.org, including but not limited to text, graphics, logos, images, software, and code, is the property of Per4ex.org or its content suppliers and is protected by copyright, trademark, and other intellectual property laws.
          </p>
          <p>
            You may not reproduce, distribute, modify, create derivative works of, publicly display, or otherwise use our content without our prior written permission.
          </p>
          <p>
            You retain ownership of any content you submit to our services, but you grant us a license to use, modify, and display such content as necessary to provide our services.
          </p>
        </div>
      </div>

      {/* Disclaimers */}
      <div className="glass-panel border-l-4 border-l-accent">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <AlertTriangle className="w-6 h-6 text-accent" />
          Disclaimers
        </h2>
        <div className="space-y-3 text-muted">
          <p>
            <strong className="text-foreground">No Warranty:</strong> Our services are provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
          </p>
          <p>
            <strong className="text-foreground">No Guarantee:</strong> We do not guarantee that our services will be uninterrupted, secure, or error-free, or that defects will be corrected.
          </p>
          <p>
            <strong className="text-foreground">Third-Party Services:</strong> Our services may integrate with or link to third-party services. We are not responsible for the availability, accuracy, or content of such third-party services.
          </p>
        </div>
      </div>

      {/* Limitation of Liability */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <Ban className="w-6 h-6 text-accent" />
          Limitation of Liability
        </h2>
        <div className="space-y-3 text-muted">
          <p>
            To the maximum extent permitted by law, Per4ex.org and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="space-y-2 list-disc pl-6">
            <li>Your use or inability to use our services</li>
            <li>Any unauthorized access to or use of our servers or data</li>
            <li>Any errors or omissions in any content</li>
            <li>Any interruption or cessation of transmission to or from our services</li>
            <li>Any bugs, viruses, or other harmful code transmitted through our services</li>
          </ul>
        </div>
      </div>

      {/* Indemnification */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4">Indemnification</h2>
        <p className="text-muted">
          You agree to indemnify, defend, and hold harmless Per4ex.org and its operators from any claims, damages, losses, liabilities, and expenses (including legal fees) arising out of or relating to your use of our services, violation of these Terms, or infringement of any rights of another party.
        </p>
      </div>

      {/* Termination */}
      <div className="glass-panel border-l-4 border-l-accent">
        <h2 className="text-2xl font-bold text-foreground mb-4">Termination</h2>
        <div className="space-y-3 text-muted">
          <p>
            We reserve the right to suspend or terminate your access to our services at any time, with or without cause or notice, for any reason, including if you breach these Terms.
          </p>
          <p>
            Upon termination, your right to use the services will immediately cease. All provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.
          </p>
        </div>
      </div>

      {/* Governing Law */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-3">
          <Gavel className="w-6 h-6 text-accent" />
          Governing Law
        </h2>
        <p className="text-muted">
          These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising from these Terms or your use of our services shall be subject to the exclusive jurisdiction of the appropriate courts.
        </p>
      </div>

      {/* Severability */}
      <div className="glass-panel">
        <h2 className="text-2xl font-bold text-foreground mb-4">Severability</h2>
        <p className="text-muted">
          If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
        </p>
      </div>

      {/* Contact */}
      <div className="glass-panel border-l-4 border-l-accent">
        <h2 className="text-2xl font-bold text-foreground mb-4">Contact Information</h2>
        <div className="space-y-3 text-muted">
          <p>
            If you have any questions about these Terms of Service, please contact us:
          </p>
          <div className="bg-background/50 p-4 rounded-lg border border-card-border">
            <p className="text-foreground font-medium mb-2">Per4ex.org</p>
            <p>Email: <a href="mailto:contact@per4ex.org" className="text-accent hover:underline">contact@per4ex.org</a></p>
            <p className="mt-2">Website: <a href="https://per4ex.org" className="text-accent hover:underline">https://per4ex.org</a></p>
          </div>
        </div>
      </div>
    </div>
  )
}

